INSERT INTO topics (topicname) VALUES ('javascript');
INSERT INTO topics (topicname) VALUES ('berlin');
INSERT INTO topics (topicname) VALUES ('dogs');

INSERT INTO users (username) VALUES ('Sylvester');
INSERT INTO users (username) VALUES ('Marilyn Manson');
INSERT INTO users (username) VALUES ('Joe Biden');
INSERT INTO users (username) VALUES ('Donald Trump');
INSERT INTO users (username) VALUES ('Pocahontas');
INSERT INTO users (username) VALUES ('Moscow Mitch');

INSERT INTO posts (user_id, topic_id, post_content) VALUES (1, 1, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (2, 1, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (3, 1, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (4, 1, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (5, 1, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (6, 1, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');

INSERT INTO posts (user_id, topic_id, post_content) VALUES (1, 2, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (2, 2, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (3, 2, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (4, 2, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (5, 2, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (6, 2, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (1, 2, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (6, 2, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (1, 2, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (6, 2, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (5, 2, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (6, 2, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');

INSERT INTO posts (user_id, topic_id, post_content) VALUES (2, 3, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (2, 3, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (3, 3, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (1, 3, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (4, 3, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (4, 3, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
INSERT INTO posts (user_id, topic_id, post_content) VALUES (6, 3, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla fugiat quia sint ipsam. Aperiam quis voluptas quas dolor, sunt velit ab, repudiandae modi obcaecati accusantium laboriosam quo minima. Pariatur, voluptatem?');
